// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvlkhEstSXx3ZGCaLuTU9CgJUfHmONrSg',
    appId: '1:847991271956:web:7c9310fce48aee08a4ed01',
    messagingSenderId: '847991271956',
    projectId: 'fir-tut-415ac',
    authDomain: 'fir-tut-415ac.firebaseapp.com',
    storageBucket: 'fir-tut-415ac.firebasestorage.app',
    measurementId: 'G-H291TGEXMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXx5AvA3BlQAxS1W8z3k3oWxGZwNExsCk',
    appId: '1:847991271956:android:1a591852bb88bb2aa4ed01',
    messagingSenderId: '847991271956',
    projectId: 'fir-tut-415ac',
    storageBucket: 'fir-tut-415ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07XOFqYFRzx7g2Mczu2qn_KwjPF5hkTE',
    appId: '1:847991271956:ios:42097611a2833215a4ed01',
    messagingSenderId: '847991271956',
    projectId: 'fir-tut-415ac',
    storageBucket: 'fir-tut-415ac.firebasestorage.app',
    iosBundleId: 'com.example.forc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07XOFqYFRzx7g2Mczu2qn_KwjPF5hkTE',
    appId: '1:847991271956:ios:42097611a2833215a4ed01',
    messagingSenderId: '847991271956',
    projectId: 'fir-tut-415ac',
    storageBucket: 'fir-tut-415ac.firebasestorage.app',
    iosBundleId: 'com.example.forc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvlkhEstSXx3ZGCaLuTU9CgJUfHmONrSg',
    appId: '1:847991271956:web:098193f82407b1caa4ed01',
    messagingSenderId: '847991271956',
    projectId: 'fir-tut-415ac',
    authDomain: 'fir-tut-415ac.firebaseapp.com',
    storageBucket: 'fir-tut-415ac.firebasestorage.app',
    measurementId: 'G-CVF859WN9J',
  );
}
